# This workflow comes from https://github.com/ofek/hatch-mypyc
# https://github.com/ofek/hatch-mypyc/blob/5a198c0ba8660494d02716cfc9d79ce4adfb1442/.github/workflows/test.yml
name: Test / anthropic

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - "integrations/anthropic/**"
      - ".github/workflows/anthropic.yml"

defaults:
  run:
    working-directory: integrations/anthropic

concurrency:
  group: cohere-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

jobs:
  run:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10"]

    steps:
      - name: Support longpaths
        if: matrix.os == 'windows-latest'
        working-directory: .
        run: git config --system core.longpaths true

      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Lint
        if: matrix.python-version == '3.9' && runner.os == 'Linux'
        run: hatch run lint:all

      - name: Run tests
        run: hatch run cov

      - name: Nightly - run unit tests with Haystack main branch
        if: github.event_name == 'schedule'
        id: nightly-haystack-main
        run: |
          hatch run pip install git+https://github.com/deepset-ai/haystack.git
          hatch run test -m "not integration"
      
      - name: Send event to Datadog for nightly failures
        if: failure() && github.event_name == 'schedule'
        uses: ./.github/actions/send_failure
        with:
          title: |
            core-integrations failure: 
            ${{ (steps.tests.conclusion == 'nightly-haystack-main') && 'nightly-haystack-main' || 'tests' }}
             - ${{ github.workflow }}
          api-key: ${{ secrets.CORE_DATADOG_API_KEY }}

      - name: Extract random contributor to these files (i.e developer who is familiar with the codebase)
        if: failure() && github.event_name == 'schedule'
        uses: ./.github/actions/extract-committers
        id: random_contributor
        with:
          project_dir: integrations/anthropic
          names_handles: '{"Madeesh Kannan":"shadeMe","Massimiliano Pippi":"masci","Stefano Fiorucci":"anakin87","Vladimir Blagojevic":"vblagoje", "Silvano Cerza": "silvanocerza", "Julian Risch": "julian-risch", "David S. Batista": "davidsbatista"}'
          default_user: "vblagoje"

      - name: Create Issue for Nightly Failure
        if: failure() && github.event_name == 'schedule'
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: |
            Nightly [${{ github.workflow }}] failed
          assignees: ${{ steps.random_contributor.outputs.user }}
          body: |
            ## Nightly Failure Report:

            > [!IMPORTANT]
            > Details on failed run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            - Branch: `${{ github.ref }}`
            - Commit: ${{ github.sha }}
            - Workflow Path: `${{ github.workflow_ref }}`

            - [ ] **Task**: Review failed CI run, fix the issue(s), and re-run until successful.
